name: Reusable workflow
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: The environment to run the workflow in
        required: true
        type: string

jobs:
  reusable_job:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Print staging environment variable
        run: echo "Staging environment variables is ${{ vars.ENV_VARIABLE }}"
      
      - name: Print staging environment secret
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
        run: echo "Staging environment secret is ${{ secrets.ENV_SECRET }} and is ${#ENV_SECRET} characters long"

      - name: Print repository variable
        run: echo "Repository variable is ${{ vars.REPO_VARIABLE }}"

      - name: Print repository secret
        env:
          REPO_SECRET: ${{ secrets.REPO_SECRET}}
        run: echo "Repository secret is ${{ secrets.REPO_SECRET }} and is ${#REPO_SECRET} characters long"