name: Reusable workflow
on:
  workflow_call:

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print staging environment variable
        run: echo "Staging environment variables is ${{ vars.env_variable }}"
      
      - name: Print staging environment secret
        run: echo "Staging environment secret is ${{ secrets.env_secret }}"