name: Reusable workflow
on:
  workflow_call:
    # inputs:
    #   ENV_VARIABLE:
    #     required: true
    #     type: string
    # secrets:
    #   ENV_SECRET:
    #     required: true

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Print staging environment variable
        run: echo "Staging environment variables is ${{ vars.ENV_VARIABLE }}"
      
      - name: Print staging environment secret
        run: echo "Staging environment secret is ${{ secrets.ENV_SECRET }}"